### ISSUE TITLE
Different Multi GPU Issue using DPO Training in different scenarios(Zero-3/precompute_log_probs/Model-Parallelism etc.)

### ISSUE THREAD

**Issue by raghavgarg97** [huggingface/trl#1117]
I am trying to train mistral model using DPO Training.
I have 4XA100s(80 GB each) but i observe that GPU mem keeps increasing during training slowly until it goes OOM.

[#1087](url) mentions similar issue ,and a comment suggested to use "gradient_checkpointing"..I tried it but Memory still keeps on increasing slowly with increasing steps.

My script is :
```import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3"
import torch
import transformers
import torch.nn as nn
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tqdm.auto import tqdm
from trl import DPOTrainer

tqdm.pandas()
from peft import (get_peft_model, LoraConfig, TaskType, prepare_model_for_int8_training)
from datasets import Dataset,DatasetDict, load_from_disk, Features, Value
from transformers import AutoModelForCausalLM,AutoTokenizer
from transformers import TrainingArguments


def print_trainable_parameters(model):
    """
    Prints the number of trainable parameters in the model.
    """
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param}"
    )

data_train=Dataset.from_pandas(pd.read_parquet("data/synthetic_prompt_data/rlhf_poc_data/train.parquet"))
data_val=Dataset.from_pandas(pd.read_parquet("data/synthetic_prompt_data/rlhf_poc_data/test.parquet"))

def return_prompt_and_responses(samples):
    return {
        "prompt": samples["prompt"],
        "chosen": samples["output_chosen"],   # rated better than k
        "rejected": samples["output_rejected"], # rated worse than j
    }

original_columns_train = data_train.column_names
original_columns_val = data_val.column_names

train_dataset=data_train.map(
    return_prompt_and_responses,
    batched=True,
    remove_columns=original_columns_train
)
eval_dataset=data_val.map(
    return_prompt_and_responses,
    batched=True,
    remove_columns=original_columns_val
)
print("*"*23)
print("Data Loaded")
print("*"*23)
model_id="models/mistral-instruct-base"

tokenizer=AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token_id=0

model = AutoModelForCausalLM.from_pretrained(
    model_id,use_cache=False,device_map='auto'
)
model_ref = AutoModelForCausalLM.from_pretrained(
    model_id ,device_map='auto'
)
for param in model_ref.parameters():
    param.requires_grad=False

print_trainable_parameters(model)
print_trainable_parameters(model_ref)

print("*"*23)
print(f"Model Loaded .Tokenizer pad token id is {tokenizer.pad_token_id}")
print("*"*23)

training_args = TrainingArguments(
    output_dir=f"models/outputs_rlhf_dpo_mistral",
    learning_rate=5.6e-5,
    save_steps=20,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    weight_decay=0.01,
    num_train_epochs=1,
    logging_steps=5,
    gradient_accumulation_steps=32,
    evaluation_strategy="steps",
    eval_steps=20,
    report_to='tensorboard',
    run_name="mistral-dpo-training",
    load_best_model_at_end=True,
    remove_unused_columns=False,
    save_total_limit=1
    
)
dpo_trainer = DPOTrainer(
    model,
    args=training_args,
    beta=0.1,
    max_length=3000,
    max_prompt_length=2500,
    max_target_length=500,
    padding_value=0,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
)
dpo_trainer.train()
dpo_trainer.save_model()```


Does anyone know why is it happening?(I have also tried loading the model on CPU,the trainer should automatically move it to GPU but then it only uses GPU 0 and throws OOM instantaneously)
Any leads will be appreciated

**Comment by raghavgarg97** [comment]
Update:
I tried to shift to Deepsped using zero-3 and flash-attention2 as mentioned in [#930](url) but got the error
```ValueError: You are attempting to perform batched generation with padding_side='right' this may lead to unexpected behaviour for Flash Attention version of Mistral. Make sure to  call `tokenizer.padding_side  = 'left'` before tokenizing the input. ```

Although I have manually set padding_side as left.
```tokenizer=AutoTokenizer.from_pretrained(model_id,padding_side='left')```

This may be because of 
```concatenated_batch[concatenated_key] = torch.cat(
                    (
                        concatenated_batch[concatenated_key],
                        pad_to_length(batch[k], max_length, pad_value=pad_value),
                    ),
                    dim=0,
                ).to(device=device)```` in dpo_trainer.py although just a speculation.


I also tried various other configurations like Zero2+ Precompute_log_probs etc, but to no advantage.
Any ideas?

**Comment by raghavgarg97** [comment]
Adding Peft Config as well to deal with OOM error leads to this error
```RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)```
as mentioned in [#958](url)

**Comment by raghavgarg97** [comment]
Update:
I am able to solve the issue by using:

- deepseed using Zero-2
- Precompute_ref_log_probs=True

```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3"
import torch
import transformers
import torch.nn as nn
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tqdm.auto import tqdm
from trl.trl import DPOTrainer

tqdm.pandas()
from peft import (get_peft_model, LoraConfig, TaskType, prepare_model_for_int8_training)
from datasets import Dataset,DatasetDict, load_from_disk, Features, Value
from transformers import AutoModelForCausalLM,AutoTokenizer,BitsAndBytesConfig
import bitsandbytes as bnb
from transformers import TrainingArguments



def print_trainable_parameters(model):
    """
    Prints the number of trainable parameters in the model.
    """
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param}"
    )

data_train=Dataset.from_pandas(pd.read_parquet("data/synthetic_prompt_data/rlhf_poc_data/train.parquet"))
data_val=Dataset.from_pandas(pd.read_parquet("data/synthetic_prompt_data/rlhf_poc_data/test.parquet"))

def return_prompt_and_responses(samples):
    return {
        "prompt": samples["prompt"],
        "chosen": samples["output_chosen"],   # rated better than k
        "rejected": samples["output_rejected"], # rated worse than j
    }

original_columns_train = data_train.column_names
original_columns_val = data_val.column_names

train_dataset=data_train.map(
    return_prompt_and_responses,
    batched=True,
    remove_columns=original_columns_train
)
eval_dataset=data_val.map(
    return_prompt_and_responses,
    batched=True,
    remove_columns=original_columns_val
)
print("*"*23)
print("Data Loaded")
print("*"*23)
model_id="models/mistral-instruct-base"

tokenizer=AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token_id=0

print("*"*23)
print(f"Tokienzer Loaded .Tokenizer pad token id is {tokenizer.pad_token_id} and {tokenizer.padding_side}")
print("*"*23)



model = AutoModelForCausalLM.from_pretrained(model_id,use_cache=False,torch_dtype=torch.float16)

print_trainable_parameters(model)


training_args = TrainingArguments(
    output_dir=f"models/outputs_rlhf_dpo_mistral",
    learning_rate=5.6e-5,
    save_steps=20,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    weight_decay=0.01,
    num_train_epochs=1,
    logging_steps=5,
    gradient_accumulation_steps=32,
    evaluation_strategy="steps",
    eval_steps=20,
    bf16=True,
    bf16_full_eval=True,
    report_to='tensorboard',
    run_name="mistral-dpo-training",
    load_best_model_at_end=True,
    remove_unused_columns=False,
    save_total_limit=1,
    gradient_checkpointing=True,
    deepspeed="./ds_config.json"
)
dpo_trainer = DPOTrainer(
    model,
    None,
    args=training_args,
    precompute_ref_log_probs=True,
    beta=0.1,
    max_length=3000,
    max_prompt_length=2500,
    max_target_length=500,
    padding_value=0,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,

)
dpo_trainer.train()
dpo_trainer.save_model()



```

**Comment by danieljohnxon** [comment]
Hi @raghavgarg97, could you elaborate on how you resolved it? I'm currently facing similar difficulties as you did with #1169. Could you advise me on what I need to do as I am still very puzzled Thank you so much!!

**Comment by raghavgarg97** [comment]
I trained it without using Peft.
Also I trained using deepspeed zero-2 instead of using Accelerate's "auto" (which is only model parallel)

**Comment by danieljohnxon** [comment]
Will it be possible to use PEFT + Deepspeed zero-2? May I know what is the configuration for the deepspeed too?

**Comment by wise-east** [comment]
@raghavgarg97 what was the mistral model size that you used? was it 7B?
