### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by TolearnMo** [huggingface/trl#1995]
### When I run the following script

```
import torch
from accelerate import Accelerator, PartialState
from peft import LoraConfig
from tqdm import tqdm
from transformers import AutoTokenizer, HfArgumentParser, pipeline

from trl import AutoModelForCausalLMWithValueHead, AutoModelForSeq2SeqLMWithValueHead, PPOConfig, PPOTrainer, set_seed
from trl.core import LengthSampler
from trl.import_utils import is_npu_available, is_xpu_available
ppo_config = PPOConfig(
    exp_name="PPO_output",
    log_with="wandb",
    task_name="PPO_output",
    model_name="/share/home/liyuefei/wangyu/positive_negative_trl/gemma2_combined_ft",     
    #query_dataset="imdb",   
    seed=42,                
    batch_size=4,
    mini_batch_size=1,
    optimize_device_cache=True, 
    gradient_accumulation_steps=1,
    reward_model="/share/home/liyuefei/wangyu/positive_negative_trl/PPO/data_preprocess_4_train_reward_model/RM-opt-350m",  
)
tokenizer = AutoTokenizer.from_pretrained("/share/home/liyuefei/wangyu/positive_negative_trl/gemma2_combined_ft",use_fast=True)
tokenizer.padding_side = 'right'
from datasets import load_dataset
bc5cdr_chemical_train_ppo = load_dataset('json', data_files='/share/home/liyuefei/wangyu/positive_negative_trl/PPO/make_ppo_dataset/bc5cdr_chemical_ppo.json',split="train")
bc5cdr_disease_train_ppo = load_dataset('json', data_files='/share/home/liyuefei/wangyu/positive_negative_trl/PPO/make_ppo_dataset/bc5cdr_disease_ppo.json',split="train")
ncbi_disease_train_ppo = load_dataset('json', data_files='/share/home/liyuefei/wangyu/positive_negative_trl/PPO/make_ppo_dataset/ncbi_disease_ppo.json',split="train")
bc5cdr_re_train_ppo = load_dataset('json', data_files='/share/home/liyuefei/wangyu/positive_negative_trl/PPO/make_ppo_dataset/bc5cdr_re_ppo.json',split="train")
chemdner_train_ppo = load_dataset('json', data_files='/share/home/liyuefei/wangyu/positive_negative_trl/PPO/make_ppo_dataset/chemdner_ppo.json',split="train")
from datasets import concatenate_datasets
ppo_data = concatenate_datasets([bc5cdr_chemical_train_ppo,
                                   bc5cdr_disease_train_ppo,
                                   ncbi_disease_train_ppo,
                                   bc5cdr_re_train_ppo,
                                   chemdner_train_ppo,
                                      ])
def process_func(example):
    text = [{'content':example['prompt'],
            'role': 'user'}]
    input_ids = tokenizer.apply_chat_template(
        text,
        padding=False,
        add_generation_prompt=True,
    )
    example['input_ids'] = input_ids
    example['query'] = tokenizer.decode(input_ids)
    return example
with PartialState().local_main_process_first():
    dataset = ppo_data.map(process_func,num_proc=4)
    dataset.set_format(type="torch")
def collator(data):
    return {key: [d[key] for d in data] for key in data[0]}
peft_config = LoraConfig(
    r=16,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM",
)
ref_model = None
device_map = {"": Accelerator().local_process_index}
import torch
from transformers import BitsAndBytesConfig
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16, #
    bnb_4bit_use_double_quant=True,
)
model = AutoModelForCausalLMWithValueHead.from_pretrained("/share/home/liyuefei/wangyu/positive_negative_trl/gemma2_combined_ft",
                                             low_cpu_mem_usage=True, 
                                             torch_dtype=torch.bfloat16,
                                             #load_in_8bit=True, 
                                             quantization_config=bnb_config,
                                             peft_config=peft_config,
                                             device_map=device_map, #"auto",
                                             attn_implementation='eager'
                                             )
ppo_trainer = PPOTrainer(ppo_config, model, ref_model, tokenizer, dataset=dataset, data_collator=collator)
device = ppo_trainer.accelerator.device
if ppo_trainer.accelerator.num_processes == 1:
    if is_xpu_available():
        device = "xpu:0"
    elif is_npu_available():
        device = "npu:0"
    else:
        device = 0 if torch.cuda.is_available() else "cpu"  # to avoid a `pipeline` bug

pipe = pipeline("text-classification", 
                model="/share/home/liyuefei/wangyu/positive_negative_trl/PPO/data_preprocess_4_train_reward_model/RM-opt-350m",
                device=device,
                torch_dtype=torch.bfloat16,
                )
generation_kwargs = {
    "min_length": -1,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True,
    #"pad_token_id": tokenizer.eos_token_id,
    "max_new_tokens": 512,
}
sent_kwargs = {"return_all_scores": True, "function_to_apply": "none", "batch_size": 16}
for batch in tqdm(ppo_trainer.dataloader):
    query_tensors = batch["input_ids"]
    response_tensors, ref_response_tensors = ppo_trainer.generate(
        query_tensors, return_prompt=False, generate_ref_response=True, **generation_kwargs
    )
    batch["response"] = tokenizer.batch_decode(response_tensors) # , skip_special_tokens=True 去除bos、start_of_turn等token
    batch["ref_response"] = tokenizer.batch_decode(ref_response_tensors) # , skip_special_tokens=True去除bos、start_of_turn等token
    texts = [q.replace("<bos><start_of_turn>user\n","").replace("<end_of_turn>\n<start_of_turn>model\n","") + 
             r.replace("<end_of_turn>\n<eos>","") for q, r in zip(batch["query"], batch["response"])]
    pipe_outputs = pipe(texts, **sent_kwargs)
    rewards = [torch.tensor(output[0]["score"]) for output in pipe_outputs]
    ref_texts = [q.replace("<bos><start_of_turn>user\n","").replace("<end_of_turn>\n<start_of_turn>model\n","") +  
                 r.replace("<end_of_turn>\n<eos>","") for q, r in zip(batch["query"], batch["ref_response"])]
    ref_pipe_outputs = pipe(ref_texts, **sent_kwargs)
    ref_rewards = [torch.tensor(output[0]["score"]) for output in ref_pipe_outputs]
    batch["ref_rewards"] = ref_rewards
    stats = ppo_trainer.step(query_tensors, response_tensors, rewards)
    ppo_trainer.log_stats(stats, batch, rewards, columns_to_log=["query", "response", "ref_response", "ref_rewards"])
ppo_trainer.save_pretrained("PPO_output")
```

### #An error occurred:
```
  5%|▌         | 72/1398 [1:12:34<24:31:08, 66.57s/it]
  5%|▌         | 73/1398 [1:13:28<23:04:12, 62.68s/it]
  5%|▌         | 74/1398 [1:14:27<22:44:01, 61.81s/it]
  5%|▌         | 75/1398 [1:15:41<24:00:52, 65.35s/it]
  5%|▌         | 76/1398 [1:16:59<25:23:21, 69.14s/it]
  6%|▌         | 77/1398 [1:18:00<24:32:19, 66.87s/it]
  6%|▌         | 78/1398 [1:19:55<29:42:52, 81.04s/it]
  6%|▌         | 79/1398 [1:20:47<26:35:48, 72.59s/it]
  6%|▌         | 80/1398 [1:21:55<26:02:53, 71.15s/it]
  6%|▌         | 81/1398 [1:22:58<25:09:01, 68.75s/it]
  6%|▌         | 82/1398 [1:24:00<24:19:39, 66.55s/it]
  6%|▌         | 83/1398 [1:25:08<24:26:56, 66.93s/it]
  6%|▌         | 84/1398 [1:26:19<24:53:58, 68.22s/it]
  6%|▌         | 85/1398 [1:27:26<24:44:34, 67.84s/it]
  6%|▌         | 86/1398 [1:28:30<24:17:14, 66.64s/it]
  6%|▌         | 87/1398 [1:29:55<26:17:09, 72.18s/it]
  6%|▋         | 88/1398 [1:31:02<25:44:02, 70.72s/it]
  6%|▋         | 89/1398 [1:32:11<25:28:13, 70.05s/it]../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [16,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [17,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [18,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [20,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [21,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [22,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [23,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [65,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [66,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [67,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [68,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [69,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [70,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [71,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [72,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [73,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [74,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [75,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [76,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [77,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [78,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [79,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [80,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [81,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [82,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [83,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [84,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [85,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [86,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [87,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [88,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [89,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [90,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [134,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

  6%|▋         | 89/1398 [1:38:09<24:03:47, 66.18s/it]
Traceback (most recent call last):
  File "/share/home/liyuefei/wangyu/positive_negative_trl/PPO/train_gemma2/PPO.py", line 124, in <module>
    pipe_outputs = pipe(texts, **sent_kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/pipelines/text_classification.py", line 156, in __call__
    result = super().__call__(*inputs, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1235, in __call__
    outputs = list(final_iterator)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1161, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/pipelines/text_classification.py", line 187, in _forward
    return self.model(**model_inputs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 1142, in forward
    transformer_outputs = self.model(
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 862, in forward
    decoder_outputs = self.decoder(
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 777, in forward
    layer_outputs = decoder_layer(
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 418, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/share/home/liyuefei/.miniconda3/envs/wy/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 192, in forward
    attn_weights, torch.tensor(torch.finfo(attn_weights.dtype).min, device=attn_weights.device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by TolearnMo** [comment]
As mentioned in this issue[@](https://github.com/huggingface/trl/issues/1941#issue-2471704567)，my gemma2-7b encountered the same problem. After setting ```attn_implementation='eager'```, it was able to run successfully, but encountered the error mentioned above again.

**Comment by RylanSchaeffer** [comment]
I don't understand. You say that it ran successfully and then also say that you hit the same error. Could you please clarify?

**Comment by TolearnMo** [comment]
> I don't understand. You say that it ran successfully and then also say that you hit the same error. Could you please clarify?
At first, I didn't set 'attd_implementation='eger', and then I encountered the problem of 'InstanceError: probability tensor contains either' inf ',' nan 'or element<0'. After setting it up, I encountered the issue of 'CUDA error: device side assert triggered' again.
batch_size>1

**Comment by TolearnMo** [comment]
> I don't understand. You say that it ran successfully and then also say that you hit the same error. Could you please clarify?


At first, I didn't set 'attd_implementation='eger', and then I encountered the problem of 'InstanceError: probability tensor contains either' inf ',' nan 'or element<0'. After setting it up, I encountered the issue of 'CUDA error: device side assert triggered' again.
batch_size>1

**Comment by sahandrez** [comment]
Hi, I'm getting the same error with SFTTrainer and Gemma 2 2B. I tried both `flash_attention_2` and `eager`. Have you found any solutions?

**Comment by RylanSchaeffer** [comment]
Are you running with bfloat16? For Gemma, this is key.

**Comment by sahandrez** [comment]
Yes, I am using bfloat16 and also set bf16 to True. Do you want me to send a reproducible code?

**Comment by RylanSchaeffer** [comment]
The answer to your question is always yes :)

**Comment by qgallouedec** [comment]
Can you also share the package versions you use? 
Try to upgrade transformers.

**Comment by sahandrez** [comment]
Thanks, I am using the latest transformers and trl releases: 
```
transformers = 4.44.2
trl = 0.10.1
CUDA = 12.1.1
torch = 2.4.0
```

### Code for Reproducing the Error
Here is a code that is basically the SFT example script from [here](https://github.com/huggingface/trl/blob/main/examples/scripts/sft.py) with the addition of `apply_chat_format`.

```python
from trl.commands.cli_utils import SFTScriptArguments, TrlParser

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM

from trl import (
    ModelConfig,
    SFTConfig,
    SFTTrainer,
    get_peft_config,
    setup_chat_format,
    get_quantization_config,
    get_kbit_device_map,
)

if __name__ == "__main__":
    parser = TrlParser((SFTScriptArguments, SFTConfig, ModelConfig))
    args, training_args, model_config = parser.parse_args_and_config()

    # Model init kwargs & Tokenizer
    quantization_config = get_quantization_config(model_config)
    model_kwargs = dict(
        revision=model_config.model_revision,
        trust_remote_code=model_config.trust_remote_code,
        attn_implementation=model_config.attn_implementation,
        torch_dtype=model_config.torch_dtype,
        use_cache=False if training_args.gradient_checkpointing else True,
        device_map=get_kbit_device_map() if quantization_config is not None else None,
        quantization_config=quantization_config,
    )
    training_args.model_init_kwargs = model_kwargs
    tokenizer = AutoTokenizer.from_pretrained(
        model_config.model_name_or_path,
        trust_remote_code=model_config.trust_remote_code,
        use_fast=True,
    )
    tokenizer.pad_token = tokenizer.eos_token

    if tokenizer.chat_template is None:
        model = AutoModelForCausalLM.from_pretrained(
            model_config.model_name_or_path, **model_kwargs
        )
        model, tokenizer = setup_chat_format(model, tokenizer)

    # Dataset
    raw_datasets = load_dataset(args.dataset_name)

    if isinstance(
        raw_datasets[args.dataset_train_split].features[training_args.dataset_text_field],
        list,
    ):

        def format_dataset(example):
            example[training_args.dataset_text_field] = tokenizer.apply_chat_template(
                example[training_args.dataset_text_field], tokenize=False
            )
            return example

        raw_datasets = raw_datasets.map(format_dataset)

    train_dataset = raw_datasets[args.dataset_train_split]
    eval_dataset = raw_datasets[args.dataset_test_split]

    # Training
    trainer = SFTTrainer(
        model=model_config.model_name_or_path,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        peft_config=get_peft_config(model_config),
    )

    trainer.train()
```

Then running the script with the following command:
```bash
python gemma_sft_test.py \
    --model_name_or_path="google/gemma-2-2b" \
    --dataset_name HuggingFaceH4/ultrafeedback_binarized \
    --dataset_train_split train_sft \
    --dataset_test_split test_sft \
    --dataset_text_field messages \
    --report_to="none" \
    --learning_rate=1.41e-5 \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 16 \
    --output_dir="logs/gemma_sft" \
    --logging_steps 1 \
    --num_train_epochs 3 \
    --max_steps -1 \
    --push_to_hub False \
    --gradient_checkpointing \
    --attn_implementation eager \
    --torch_dtype bfloat16 \
    --bf16 \
```

## Behavior
* When I use `google/gemma-2-2b` I get `RuntimeError: CUDA error: device-side assert triggered` similar to the error posted by the OP. 
* When I use `facebook/opt-350m` this error does not happen and the model seems to be training.
* Interestingly, if I do not use `apply_chat_template` and use the default dataset for SFT (`timdettmers/openassistant-guanaco`) Gemma 2-2B seems to be training. Perhaps there is an issue with applying the chat template? But note that I have to use `apply_chat_template` with the `HuggingFaceH4/ultrafeedback_binarized` because otherwise the `SFTTrainer` gives the error of `ValueError: text input must be of type str (single example), List[str] (batch or single pretokenized example) or List[List[str]] (batch of pretokenized examples).`.

**Comment by sahandrez** [comment]
Thanks, I am using the latest transformers and trl releases: 
```
transformers = 4.44.2
trl = 0.10.1
CUDA = 12.1.1
torch = 2.4.0
```
Actually, while creating the minimal code, I was able to resolve the error. It was due to the `apply_chat_template` function. But interestingly, the same code was working fine with `facebook/opt-350` and was failing with `google/gemma-2-2b`.

**Comment by RylanSchaeffer** [comment]
For others who come along, can you explain what "It was due to the apply_chat_template function. " meant? How did you fix this?

**Comment by RylanSchaeffer** [comment]
@qgallouedec , between this issue and [my previous issue on the exact same topic](https://github.com/huggingface/trl/issues/1941), I think you should consider closing this issue.

**Comment by sahandrez** [comment]
I have this line in my code that sets up the model for chat template and applies the chat template to the dataset in case needed: 
```python
if tokenizer.chat_template is None:
        model = AutoModelForCausalLM.from_pretrained(
            model_config.model_name_or_path, **model_kwargs
        )
        model, tokenizer = setup_chat_format(model, tokenizer)
```
But, instead of passing the actual initialized model to `SFTTrainer`, I was passing `model_config.model_name_or_path` to it similar to the example [here](https://github.com/huggingface/trl/blob/v0.9.6/examples/scripts/sft.py). Passing the initialized model to the `SFTTrainer` resolved the `RuntimeError: CUDA error: device-side assert triggered`. What is still a bit confusing to me is that the same code has been working fine with other models such as `facebook/opt-350m`.
