### ISSUE TITLE
is_async_output_supported is not implemented error When GRPO training with use_vllm=True

### ISSUE THREAD

**Issue by nomadlx** [huggingface/trl#2816]
### Reproduction

code:
```
from datasets import load_dataset
from trl import GRPOConfig, GRPOTrainer

dataset = load_dataset("trl-lib/tldr", split="train")

# Define the reward function, which rewards completions that are close to 20 characters
def reward_len(completions, **kwargs):
    return [-abs(20 - len(completion)) for completion in completions]

training_args = GRPOConfig(
    output_dir="Qwen2-14B-GRPO",
    bf16=True,
    use_vllm=True,
    deepspeed="ds_config/deepspeed/ds_z3_offload_config.json"
)
trainer = GRPOTrainer(
    model="Qwen/Qwen2.5-14B-Instruct",
    reward_funcs=reward_len,
    args=training_args,
    train_dataset=dataset,
)
trainer.train()
```

error info:
```
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
INFO 02-10 09:28:56 config.py:542] This model supports multiple tasks: {'embed', 'generate', 'classify', 'reward', 'score'}. Defaulting to 'generate'.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/train_example/train_example_grpo_office.py", line 20, in <module>
[rank0]:     trainer = GRPOTrainer(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/trl/trainer/grpo_trainer.py", line 313, in __init__
[rank0]:     self.llm = LLM(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 1051, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 242, in __init__
[rank0]:     self.llm_engine = self.engine_class.from_engine_args(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 481, in from_engine_args
[rank0]:     engine_config = engine_args.create_engine_config(usage_context)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 1276, in create_engine_config
[rank0]:     config = VllmConfig(
[rank0]:   File "<string>", line 19, in __init__
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 3206, in __post_init__
[rank0]:     self.model_config.verify_async_output_proc(self.parallel_config,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 677, in verify_async_output_proc
[rank0]:     if not current_platform.is_async_output_supported(self.enforce_eager):
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/interface.py", line 201, in is_async_output_supported
[rank0]:     raise NotImplementedError
[rank0]: NotImplementedError
[rank0]:[W210 09:28:57.746609535 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
etuning-grpo-qwen25-14b-lora-exp1-1-worker-0:24330:24759 [0] NCCL INFO [Service thread] Connection closed by localRank 0
etuning-grpo-qwen25-14b-lora-exp1-1-worker-0:24330:25660 [0] NCCL INFO comm 0x55fba1b35ef0 rank 0 nranks 7 cudaDev 0 busId 53000 - Abort COMPLETE
W0210 09:28:58.769000 24189 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 24331 closing signal SIGTERM
W0210 09:28:58.769000 24189 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 24332 closing signal SIGTERM
W0210 09:28:58.770000 24189 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 24333 closing signal SIGTERM
W0210 09:28:58.770000 24189 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 24334 closing signal SIGTERM
W0210 09:28:58.771000 24189 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 24335 closing signal SIGTERM
W0210 09:28:58.771000 24189 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 24336 closing signal SIGTERM
E0210 09:28:59.600000 24189 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 24330) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1165, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 799, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_example_grpo_office.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-10_09:28:58
  host      : etuning-grpo-qwen25-14b-lora-exp1-1-worker-0.etuning-grpo-qwen25-14b-lora-exp1-1-worker.llm.svc.cluster.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24330)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### System Info

python: 3.10.12
CUDA Version: 12.3
accelerate: 0.34.2
transformers: 4.48.3
torch: 2.5.1
trl: 0.14.0
vllm: 0.7.2

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by jymChen** [comment]
Run `pip install vllm==0.7.1`, and it works.

**Comment by dotku** [comment]
We can't just keep using the lower version :(
