### ISSUE TITLE
vllm torch.distributed.DistStoreError: wait timeout

### ISSUE THREAD

**Issue by Ozawakun97** [huggingface/trl#3221]
### Reproduction

I successfully run the training with vllm but after several iterations it shows the following bug:
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/run_grpo_szfs.py", line 310, in <module>
[rank0]:     main()
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/run_grpo_szfs.py", line 306, in main
[rank0]:     grpo_function(model_args, script_args, training_args)
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/run_grpo_szfs.py", line 264, in grpo_function
[rank0]:     train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2241, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2548, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3692, in training_step
[rank0]:     inputs = self._prepare_inputs(inputs)
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/trl_local/trl/extras/profiling.py", line 87, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/trl_local/trl/trainer/grpo_trainer.py", line 647, in _prepare_inputs
[rank0]:     inputs = self._generate_and_score_completions(inputs)
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/trl_local/trl/trainer/grpo_trainer.py", line 677, in _generate_and_score_completions
[rank0]:     self._move_model_to_vllm()
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/trl_local/trl/extras/profiling.py", line 87, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/trl_local/trl/trainer/grpo_trainer.py", line 636, in _move_model_to_vllm
[rank0]:     self.vllm_client.update_named_param(name, param.data)
[rank0]:   File "/mnt/data/wenhanlin/Distributed_GRPO/trl_local/trl/extras/vllm_client.py", line 235, in update_named_param
[rank0]:     self.pynccl_comm.group.barrier()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/utils.py", line 212, in barrier
[rank0]:     self.broadcast_obj(None, src=i)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/utils.py", line 190, in broadcast_obj
[rank0]:     recv_obj = pickle.loads(self.store.get(key))
[rank0]: torch.distributed.DistStoreError: wait timeout after 300000ms, keys: /broadcast_from/0/52214

### System Info

- Platform: Linux-5.10.134-008.12.kangaroo.al8.x86_64-x86_64-with-glibc2.35
- Python version: 3.10.12
- TRL version: 0.16.0
- PyTorch version: 2.6.0
- CUDA device(s): NVIDIA A800-SXM4-80GB, NVIDIA A800-SXM4-80GB, NVIDIA A800-SXM4-80GB, NVIDIA A800-SXM4-80GB, NVIDIA A800-SXM4-80GB, NVIDIA A800-SXM4-80GB, NVIDIA A800-SXM4-80GB, NVIDIA A800-SXM4-80GB
- Transformers version: 4.49.0
- Accelerate version: 1.0.0
- Accelerate config: not found
- Datasets version: 3.5.0
- HF Hub version: 0.29.3
- bitsandbytes version: not installed
- DeepSpeed version: 0.16.5
- Diffusers version: 0.30.3
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.66.5
- PEFT version: not installed
- vLLM version: 0.8.0

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by wilrop** [comment]
I've been running into the same issues over and over. This now seems to happen with and without setting the flag `export NCCL_P2P_DISABLE=1` so I believe this may not be the problem after all.

**Comment by wilrop** [comment]
This issue seems to be impacting many people. I believe the following issues are also dealing with the same problem:
- https://github.com/huggingface/trl/issues/3157
- https://github.com/huggingface/trl/issues/3214

**Comment by thesillystudent** [comment]
@wilrop were you able to fix this ?

**Comment by wilrop** [comment]
No, not yet. I hope this will get additional attention soon because it enormously hinders training. 

Anecdotally, it seems that this issue only occurs in the setting where 1 GPU is used for vLLM generation and 1 other GPU for training. My training run where 1 GPU is used for vLLM and another 4 for training has been running for longer than it took my other experiments to crash. Have others also noticed that?

**Comment by thesillystudent** [comment]
For me 1 GPU for vLLM and 3 GPUs for Training ran for more than 1 pass of the train set and then failed.

**Comment by Techie5879** [comment]
Same. Running trl serve on GPU 0 and GRPO on GPU 1, have the same DistStoreError after ~80 ish steps

**Comment by cii030** [comment]
same issue :(

**Comment by PrinceJayJiao** [comment]
I hope this can be fixed quickly

**Comment by shanghongsim** [comment]
Hi everyone, I just got a similar error but managed to fix it.

## The setup
TRL version: 0.16.0
Accelerate version: 1.6.0
Deepspeed version: 0.16.4
vllm version: 0.7.3
Transformers version: 4.51.3

## Commands

Starting vllm server:
```bash
CUDA_VISIBLE_DEVICES=0 trl vllm-serve --model shanghong/stage1
```

Launching training script:
```bash
#!/bin/bash
export TORCH_CPP_LOG_LEVEL=INFO NCCL_DEBUG=None
export CUDA_VISIBLE_DEVICES="2,3,4,5"

task="grpo" 

ACCELERATE_LOG_LEVEL=info accelerate launch \
--main_process_port 25678 --config_file training_configs/deepspeed_zero3_cpu.yaml \
${task}.py \
training_configs/${task}_full.yaml
```

## The error
![Image](https://github.com/user-attachments/assets/c7752740-7f69-4567-a4f5-95ab73b50ac9)

## The fix
Managed to fix the error by downgrading accerelate from 1.6.0 to 1.4.0.

**Comment by behroozazarkhalili** [comment]
For anyone still landing here: this looks **resolved by upgrading trl** — as @shanghongsim noted above, moving off the 0.16 stack fixed the `DistStoreError: wait timeout`.

Separately, on current `main` (vLLM 0.22, 2× H100) I ran a single-node server-mode GRPO smoke through several weight-sync cycles and saw **no `DistStoreError` / NCCL timeout** at the `VLLMClient` sync path. So the basic case appears fixed on recent versions. (Multi-node setups can still hit store/timeout issues for unrelated reasons — those would be worth a fresh report with versions if anyone sees them.)

cc @qgallouedec @kashif — appears safe to close given the confirmed fix-by-upgrade.

**Comment by albertvillanova** [comment]
Hey @HennyWen, sorry for the very slow reply — we're catching up on the backlog. 

This `DistStoreError: wait timeout` at the pynccl weight-sync barrier has since been resolved. In 0.16 the vLLM client hardcoded the NCCL communicator to `cuda:0`; on current TRL the device is parameterized (see https://github.com/huggingface/trl/blob/e7ffa913e507c23aa0e7747f69bc1908977eeb18/trl/generation/vllm_client.py#L416-L485), which fixes the NCCL device conflicts between the vLLM server and the trainers — exactly the case that bit hardest when generation and training sat on separate GPUs (PR #3762) — and a retry strategy was added to the client (#4845). Several people confirmed upgrading off the 0.16 stack (0.17.0+) resolves it, and a fresh smoke test on current `main` showed no timeout. 

Closing as fixed; please re-open with a new report and `trl env` if you still hit it on a current version (multi-node setups can still see unrelated store/timeouts). Related: #3157 was closed for the same reason.
