### ISSUE TITLE
GRPO + vLLM colocate + PEFT hangs

### ISSUE THREAD

**Issue by RobHessQ** [huggingface/trl#3671]
### Reproduction

Hi,

The combination of the GRPOTrainer with the colocate vLLM backend and PEFT are causing hanging issues on my system. The trainer will often perform only one, but sometimes two or three iterations before hanging without any message. This issue happens only on multi-gpu setups. I've tested several combinations of vLLM mode and PEFT, as is summarised by the table:

|       | vLLM Server | vLLM Colocate |
|-------|-------------|---------------|
| No PEFT   | ✅          | ✅            |
| PEFT | ✅          | ❌            |

For server, I ran:

```bash
CUDA_VISIBLE_DEVICES=0 trl vllm-serve --model Qwen/Qwen2-0.5B-Instruct --tensor-parallel-size 1 --data-parallel-size 1
```
and
```bash
CUDA_VISIBLE_DEVICES=1 accelerate launch minimal.py --mode "server" --use_peft
```

For colocate, I ran:
```bash
accelerate launch minimal.py --mode "colocate" --use_peft
```
You can remove the `--use_peft` flag to turn off PEFT. Below you can find a minimal example to reproduce my results. 

```python minimal.py
import argparse

import torch
from datasets import load_dataset
from peft import LoraConfig
from trl import GRPOConfig, GRPOTrainer


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--use_peft", default=False, action="store_true")
    args = parser.parse_args()

    # Dataset
    dataset = load_dataset("trl-lib/tldr", split="train")

    # Reward fn
    def reward_len(completions, **kwargs):
        """Reward completions close to 20 chars"""
        return [-abs(20 - len(completion)) for completion in completions]

    # Peft config
    peft_config = None
    if args.use_peft:
        peft_config = LoraConfig(
            task_type="CAUSAL_LM",
            r=8,
            lora_alpha=16,
            lora_dropout=0.1,
            target_modules="all-linear",
        )

    # Trainer args
    training_args = GRPOConfig(
        output_dir="Qwen2-0.5B-GRPO",
        bf16=True,
        use_vllm=True,
        vllm_mode="colocate",
        vllm_tensor_parallel_size=torch.cuda.device_count(),
        vllm_gpu_memory_utilization=0.3,
        report_to=[],
        logging_steps=1,
    )

    # Trainer
    trainer = GRPOTrainer(
        model="Qwen/Qwen2-0.5B-Instruct",
        reward_funcs=reward_len,
        args=training_args,
        train_dataset=dataset,
        peft_config=peft_config,
    )

    # let's go!
    trainer.train()


if __name__ == "__main__":
    main()
```

outputs:

```
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `2`
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
INFO 06-30 11:56:17 [importing.py:53] Triton module has been replaced with a placeholder.
INFO 06-30 11:56:17 [importing.py:53] Triton module has been replaced with a placeholder.
INFO 06-30 11:56:17 [__init__.py:239] Automatically detected platform cuda.
INFO 06-30 11:56:17 [__init__.py:239] Automatically detected platform cuda.
PEFT: True
Mode:PEFT: colocate
 True
Mode: colocate
[2025-06-30 11:56:27,551] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /cache_dir/triton, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
[2025-06-30 11:56:28,148] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /cache_dir/triton, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
INFO 06-30 11:56:45 [config.py:717] This model supports multiple tasks: {'score', 'classify', 'reward', 'generate', 'embed'}. Defaulting to 'generate'.
INFO 06-30 11:56:45 [config.py:1729] Disabling V1 multiprocessing for external launcher.
INFO 06-30 11:56:45 [config.py:2003] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 06-30 11:56:46 [config.py:717] This model supports multiple tasks: {'reward', 'score', 'generate', 'embed', 'classify'}. Defaulting to 'generate'.
INFO 06-30 11:56:46 [config.py:1729] Disabling V1 multiprocessing for external launcher.
INFO 06-30 11:56:46 [config.py:2003] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 06-30 11:56:46 [core.py:58] Initializing a V1 LLM engine (v0.8.5.post1) with config: model='Qwen/Qwen2-0.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-0.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=768, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='auto', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2-0.5B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
WARNING 06-30 11:56:47 [utils.py:2522] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7f1b3ba3f550>
INFO 06-30 11:56:47 [core.py:58] Initializing a V1 LLM engine (v0.8.5.post1) with config: model='Qwen/Qwen2-0.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2-0.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=768, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='auto', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2-0.5B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
WARNING 06-30 11:56:48 [utils.py:2522] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fda1e29f5b0>
INFO 06-30 11:56:48 [utils.py:1055] Found nccl from library libnccl.so.2
INFO 06-30 11:56:48 [pynccl.py:69] vLLM is using nccl==2.21.5
INFO 06-30 11:56:48 [utils.py:1055] Found nccl from library libnccl.so.2
INFO 06-30 11:56:48 [pynccl.py:69] vLLM is using nccl==2.21.5
INFO 06-30 11:56:49 [custom_all_reduce_utils.py:244] reading GPU P2P access cache from /usr2/username/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 06-30 11:56:49 [custom_all_reduce_utils.py:244] reading GPU P2P access cache from /usr2/username/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 06-30 11:56:49 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_33fed6d7'), local_subscribe_addr='ipc:///tmp/ef254e37-d2c5-4217-9534-2d4ba82c35ff', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 06-30 11:56:49 [parallel_state.py:1004] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1
INFO 06-30 11:56:49 [parallel_state.py:1004] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 06-30 11:56:49 [cuda.py:221] Using Flash Attention backend on V1 engine.
INFO 06-30 11:56:49 [cuda.py:221] Using Flash Attention backend on V1 engine.
WARNING 06-30 11:56:49 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
WARNING 06-30 11:56:49 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 06-30 11:56:49 [gpu_model_runner.py:1329] Starting to load model Qwen/Qwen2-0.5B-Instruct...
INFO 06-30 11:56:49 [gpu_model_runner.py:1329] Starting to load model Qwen/Qwen2-0.5B-Instruct...
INFO 06-30 11:56:49 [weight_utils.py:265] Using model weights format ['*.safetensors']
INFO 06-30 11:56:49 [weight_utils.py:265] Using model weights format ['*.safetensors']
INFO 06-30 11:56:49 [weight_utils.py:315] No model.safetensors.index.json found in remote.
INFO 06-30 11:56:50 [loader.py:458] Loading weights took 0.17 seconds
INFO 06-30 11:56:50 [weight_utils.py:315] No model.safetensors.index.json found in remote.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  6.03it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  6.02it/s]

INFO 06-30 11:56:50 [loader.py:458] Loading weights took 0.20 seconds
INFO 06-30 11:56:50 [gpu_model_runner.py:1347] Model loading took 0.4643 GiB and 0.778950 seconds
INFO 06-30 11:56:50 [gpu_model_runner.py:1347] Model loading took 0.4643 GiB and 1.036269 seconds
INFO 06-30 11:56:59 [backends.py:420] Using cache directory: /usr2/username/.cache/vllm/torch_compile_cache/f5bc2eff9a/rank_1_0 for vLLM's torch.compile
INFO 06-30 11:56:59 [backends.py:430] Dynamo bytecode transform time: 8.74 s
INFO 06-30 11:56:59 [backends.py:420] Using cache directory: /usr2/username/.cache/vllm/torch_compile_cache/f5bc2eff9a/rank_0_0 for vLLM's torch.compile
INFO 06-30 11:56:59 [backends.py:430] Dynamo bytecode transform time: 8.56 s
INFO 06-30 11:57:05 [backends.py:118] Directly load the compiled graph(s) for shape None from the cache, took 6.233 s
INFO 06-30 11:57:06 [backends.py:118] Directly load the compiled graph(s) for shape None from the cache, took 6.352 s
INFO 06-30 11:57:07 [monitor.py:33] torch.compile takes 8.74 s in total
INFO 06-30 11:57:07 [monitor.py:33] torch.compile takes 8.56 s in total
INFO 06-30 11:57:08 [kv_cache_utils.py:634] GPU KV cache size: 6,122,816 tokens
INFO 06-30 11:57:08 [kv_cache_utils.py:634] GPU KV cache size: 6,122,816 tokens
INFO 06-30 11:57:08 [kv_cache_utils.py:637] Maximum concurrency for 768 tokens per request: 7972.42x
INFO 06-30 11:57:08 [kv_cache_utils.py:637] Maximum concurrency for 768 tokens per request: 7972.42x
INFO 06-30 11:57:34 [custom_all_reduce.py:195] Registering 3283 cuda graph addresses
INFO 06-30 11:57:34 [custom_all_reduce.py:195] Registering 3283 cuda graph addresses
INFO 06-30 11:57:34 [gpu_model_runner.py:1686] Graph capturing finished in 26 secs, took 0.37 GiB
INFO 06-30 11:57:34 [gpu_model_runner.py:1686] Graph capturing finished in 26 secs, took 0.37 GiB
INFO 06-30 11:57:34 [core.py:159] init engine (profile, create kv cache, warmup model) took 44.57 seconds
INFO 06-30 11:57:34 [core.py:159] init engine (profile, create kv cache, warmup model) took 44.23 seconds
[rank1]:[W630 11:57:35.163415352 ProcessGroupNCCL.cpp:4561] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. Specify device_ids in barrier() to force use of a particular device, or call init_process_group() with a device_id.
[rank0]:[W630 11:57:35.178621564 ProcessGroupNCCL.cpp:4561] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. Specify device_ids in barrier() to force use of a particular device, or call init_process_group() with a device_id.
  0%|                                                                                                                                           | 0/175083 [00:00<?, ?it/s]INFO 06-30 11:57:37 [block_pool.py:264] Successfully reset prefix cache
INFO 06-30 11:57:37 [block_pool.py:264] Successfully reset prefix cache
[rank1]:[W630 11:57:39.898826948 reducer.cpp:1400] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W630 11:57:39.902000567 reducer.cpp:1400] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
  0%|                                                                                                                                                                                                                       {'loss': 0.1139, 'grad_norm': 0.4000445008277893, 'learning_rate': 1e-06, 'num_tokens': 9498.0, 'completions/mean_length': 244.625, 'completions/min_length': 74.0, 'completions/max_length': 256.0, 'completions/clipped_ratio': 0.875, 'completions/mean_terminated_length': 74.0, 'completions/min_terminated_length': 74.0, 'completions/max_terminated_length': 74.0, 'rewards/reward_len/mean': -993.9375, 'rewards/reward_len/std': 225.0850067138672, 'reward': -993.9375, 'reward_std': 209.34071350097656, 'frac_reward_zero_std': 0.0, 'kl': 0.0, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.0}
  0%|                                                                                                                               | 1/175083 [00:03<147:55:56,  3.04s/it]INFO 06-30 11:57:40 [block_pool.py:264] Successfully reset prefix cache
INFO 06-30 11:57:40 [block_pool.py:264] Successfully reset prefix cache
  0%|                                                                                                                                                                                                                       {'loss': 0.0, 'grad_norm': 0.7850744128227234, 'learning_rate': 9.99994288423205e-07, 'num_tokens': 17650.0, 'completions/mean_length': 256.0, 'completions/min_length': 256.0, 'completions/max_length': 256.0, 'completions/clipped_ratio': 1.0, 'completions/mean_terminated_length': 0.0, 'completions/min_terminated_length': 0.0, 'completions/max_terminated_length': 0.0, 'rewards/reward_len/mean': -1178.25, 'rewards/reward_len/std': 328.59326171875, 'reward': -1178.25, 'reward_std': 263.5120544433594, 'frac_reward_zero_std': 0.0, 'kl': 0.0005408637225627899, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.0}
  0%|                                                                                                                               | 2/175083 [00:05<123:17:39,  2.54s/it]INFO 06-30 11:57:42 [block_pool.py:264] Successfully reset prefix cache
INFO 06-30 11:57:42 [block_pool.py:264] Successfully reset prefix cache
  0%|                                                                                                                                                                                                                       {'loss': 0.1346, 'grad_norm': 0.6792234182357788, 'learning_rate': 9.9998857684641e-07, 'num_tokens': 26399.0, 'completions/mean_length': 243.3125, 'completions/min_length': 53.0, 'completions/max_length': 256.0, 'completions/clipped_ratio': 0.875, 'completions/mean_terminated_length': 53.0, 'completions/min_terminated_length': 53.0, 'completions/max_terminated_length': 53.0, 'rewards/reward_len/mean': -1119.3125, 'rewards/reward_len/std': 334.5872497558594, 'reward': -1119.3125, 'reward_std': 287.9966735839844, 'frac_reward_zero_std': 0.0, 'kl': 0.0005186283378861845, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.0}
  0%|                                                                                                                               | 3/175083 [00:07<115:07:18,  2.37s/it]INFO 06-30 11:57:44 [block_pool.py:264] Successfully reset prefix cache
INFO 06-30 11:57:44 [block_pool.py:264] Successfully reset prefix cache
  0%|                                                                                                                                                                                                                       {'loss': 0.0, 'grad_norm': 0.7822123169898987, 'learning_rate': 9.99982865269615e-07, 'num_tokens': 35543.0, 'completions/mean_length': 256.0, 'completions/min_length': 256.0, 'completions/max_length': 256.0, 'completions/clipped_ratio': 1.0, 'completions/mean_terminated_length': 0.0, 'completions/min_terminated_length': 0.0, 'completions/max_terminated_length': 0.0, 'rewards/reward_len/mean': -1120.0, 'rewards/reward_len/std': 254.02835083007812, 'reward': -1120.0, 'reward_std': 158.6692352294922, 'frac_reward_zero_std': 0.0, 'kl': 0.0005183961475268006, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.0}
  0%|                                                                                                                               | 4/175083 [00:09<112:23:58,  2.31s/it]INFO 06-30 11:57:46 [block_pool.py:264] Successfully reset prefix cache
INFO 06-30 11:57:46 [block_pool.py:264] Successfully reset prefix cache
  0%|                                                                                                                                                                                                                       {'loss': 0.1295, 'grad_norm': 0.5892613530158997, 'learning_rate': 9.9997715369282e-07, 'num_tokens': 44744.0, 'completions/mean_length': 240.0625, 'completions/min_length': 90.0, 'completions/max_length': 256.0, 'completions/clipped_ratio': 0.75, 'completions/mean_terminated_length': 128.5, 'completions/min_terminated_length': 90.0, 'completions/max_terminated_length': 167.0, 'rewards/reward_len/mean': -1028.3125, 'rewards/reward_len/std': 231.5572509765625, 'reward': -1028.3125, 'reward_std': 233.8431396484375, 'frac_reward_zero_std': 0.0, 'kl': 0.00046767923049628735, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.0}
  0%|                                                                                                                               | 5/175083 [00:11<109:05:42,  2.24s/it]INFO 06-30 11:57:48 [block_pool.py:264] Successfully reset prefix cache
INFO 06-30 11:57:48 [block_pool.py:264] Successfully reset prefix cache
  0%|                                                                                                                                                                                                                       {'loss': 0.102, 'grad_norm': 0.5307900905609131, 'learning_rate': 9.99971442116025e-07, 'num_tokens': 53081.0, 'completions/mean_length': 244.5625, 'completions/min_length': 90.0, 'completions/max_length': 256.0, 'completions/clipped_ratio': 0.75, 'completions/mean_terminated_length': 164.5, 'completions/min_terminated_length': 90.0, 'completions/max_terminated_length': 239.0, 'rewards/reward_len/mean': -938.5, 'rewards/reward_len/std': 230.05043029785156, 'reward': -938.5, 'reward_std': 235.205322265625, 'frac_reward_zero_std': 0.0, 'kl': 0.0005211391253396869, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.0}
  0%|                                                                                                                               | 6/175083 [00:13<107:38:12,  2.21s/it]INFO 06-30 11:57:50 [block_pool.py:264] Successfully reset prefix cache
INFO 06-30 11:57:50 [block_pool.py:264] Successfully reset prefix cache
```
*NOTE*: Some lines are hidden by markdown. 

### Things I Have Tried That Did Not Work:
- `export NCCL_P2P_DISABLE=1`
- `export NCCL_IB_DISABLE=1`
- `export NCCL_SOCKET_FAMILY=AF_INET`
- vLLM `0.7.2`, `0.8.2`, `0.8.4`, `0.8.5` and `0.9.1`
- Transformers `4.50`, `4.52`
- Varying `vllm_gpu_memory_utilization`

### System Info

- Platform: Linux-5.15.0-130-generic-x86_64-with-glibc2.35
- Python version: 3.10.0
- TRL version: 0.18.0
- PyTorch version: 2.6.0+cu124
- accelerator(s): NVIDIA A100-SXM4-80GB, NVIDIA A100-SXM4-80GB
- Transformers version: 4.52.3
- Accelerate version: 1.4.0
- Accelerate config: not found
- Datasets version: 3.3.2
- HF Hub version: 0.33.0
- bitsandbytes version: not installed
- DeepSpeed version: 0.16.8
- Diffusers version: not installed
- Liger-Kernel version: 0.5.10
- LLM-Blender version: not installed
- OpenAI version: 1.65.4
- PEFT version: 0.15.2
- vLLM version: 0.8.5.post1

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by ankur6ue** [comment]
in vllm server mode, are the changes to the LORA matrices being propagated to vllm server? See: 
https://github.com/huggingface/trl/issues/3661

If the LORA matrix changes are not propagated to vllm, training won't work correctly.. as the generations would always use the old model..

**Comment by shirinyamani** [comment]
Hello @ankur6ue  thanks for excellent description of the problem. 
I see what you mean. I am going to inspect when we move the model to vllm here
https://github.com/huggingface/trl/blob/e04f7eb3b993b5278733a793853ed3a85d1c69c8/trl/trainer/grpo_trainer.py#L930
is it actually the peft model? have you inspected this?

**Comment by RobHessQ** [comment]
Concerning the worry @ankur6ue raised, running the script in my post with `learning_rate=1e-3` and `--use_peft` shows that the lora model quickly learns to output a small number of characters. I also wrote a callback that prints the mean of LoRA weights, showing that they change with each iteration. 

Concluding, LoRA adapters in server mode seem to work as they should. However, they don't work as they should in colocate mode. 

@shirinyamani I'll check the GRPOTrainer to make sure the PEFT model is sent to the vLLM server.

**Comment by RobHessQ** [comment]
@shirinyamani I have investigated the code in line 930 and confirmed that, in colocate mode,
- The model is correctly identified and treated as a PEFT model,
- LoRA adapters are merged every iteration before the vLLM backend is called.

I then identified the line where the code hangs. This occurs here:

https://github.com/huggingface/trl/blob/e04f7eb3b993b5278733a793853ed3a85d1c69c8/trl/trainer/grpo_trainer.py#L1171

So things must be hanging `self.llm.generate` function in colocate mode in a way that does not happen for server mode.

**Comment by shon-otmazgin-wix** [comment]
the issue getting worse using bnb. the weights merging every iteration raise warnings for 4bit merges.

**Comment by TaeSanKIM** [comment]
same issue with @shon-otmazgin-wix. 
bnb for 4bit training has also raised assertion error for server mode (but it's ok for 8bit training not loading bnb).

**Comment by sunCityDaa** [comment]
same error

**Comment by yeshsurya** [comment]
+1 Same issue

**Comment by Graysonggg** [comment]
same issue

**Comment by ckddls2023** [comment]
+1 Same issue

**Comment by The-Inscrutable-X** [comment]
To confirm, server mode does update and sync the LoRA weights to vllm?

**Comment by KMKoushik** [comment]
any updates on this?

**Comment by zhiqihuang** [comment]
Hi team, 

Thanks for bring this up. Does `trl vllm-serve` automatically handle the LoRA module?

My training job is like this.

1. Start the vLLM server, for example 
`CUDA_VISIBLE_DEVICES=0 trl vllm-serve --model google/gemma-2-2b-it --port 8080`

2. Then, start the training script, for example, `CUDA_VISIBLE_DEVICES=1 accelerate launch train.py`

In `train.py`, the GRPOTrainer has `peft_config`, so only LoRA weights are getting trained. For example
```
grpo_config = GRPOConfig(
    ........
    use_vllm=True,
    vllm_server_port="8080",
)
```
and 
```
trainer = GRPOTrainer(
    ........
    args=grpo_config,
    peft_config=peft_config,
)
```
But in `trl vllm-serve` command, I only load the original model `google/gemma-2-2b-it`, the server does not have LoRA adapter. When the client sends the updated weights to the server, what params are being updated? Or am I doing this wrong?

Update: AI says 

"In your current workflow, you are likely generating text using the frozen base model throughout the entire training process, which means your policy will not improve (flat reward curve) because the generations do not reflect the updated LoRA weights."

Which is not true, I did observe the reward increases during training.

**Comment by ChengHu98** [comment]
> same issue with [@shon-otmazgin-wix](https://github.com/shon-otmazgin-wix). bnb for 4bit training has also raised assertion error for server mode (but it's ok for 8bit training not loading bnb).

Did you solve this problems?

**Comment by phisad** [comment]
> But in `trl vllm-serve` command, I only load the original model `google/gemma-2-2b-it`, the server does not have LoRA adapter. When the client sends the updated weights to the server, what params are being updated? Or am I doing this wrong?

The sync should automatically happen during `_generate_single_turn`. See L1166-1171 in `grpo_trainer.py` (version 0.28)

```Python
        if self.use_vllm:
            # Sync weights if training step changed
            if self.state.global_step != self._last_loaded_step:
                with profiling_context(self, "sync_weights"):
                    self.vllm_generation.sync_weights()
                self._last_loaded_step = self.state.global_step
```
Have a look at `sync_weights` to see the param updates. It's a rather long one and very case-dependent.

**Comment by skp-github** [comment]
I ran into the same issue while using 8× NVIDIA A40 GPUs. After switching to newer hardware, the problem was resolved, it worked without errors on 8× NVIDIA H200 GPUs.

P.S. I also tested the serve mode, but encountered some weight synchronization issues. I haven’t had a chance to investigate that further yet.

**Comment by albertvillanova** [comment]
Hey @RobHessQ, sorry for the very late reply — catching up on the backlog. 

Apologies this one sat for so long: it's a real, reproducible report with a clean MWE, several +1s, and a precise self-diagnosis (hang at `llm.generate` in colocate mode with adapters merged). Since you opened this, the vLLM integration in GRPO was substantially refactored — generation now lives in [`trl/generation/vllm_generation.py`](https://github.com/huggingface/trl/blob/51c6d3ca31fb4cc80ff719c0844bbdfcd0feeefb/trl/generation/vllm_generation.py#L439-L526) and colocate became the default mode. The PEFT branch of `sync_weights` still merges → loads to vLLM → unmerges in roughly the same shape you saw, but the surrounding pipeline differs. Could you (or anyone on this thread) re-test the MWE on a current TRL (`pip install -U trl`, ≥0.28) with vLLM ≥0.11 and report whether the hang persists? @skp-github's note that H200s work but A40/A100 don't is a useful clue — if the hang is hardware/NCCL-specific around colocate+PEFT we'll want to scope a workaround or warning.

**Comment by RobHessQ** [comment]
Hi, 

Thanks for coming back to this. I have since moved on to a different project and don't have to time to test the new version, I'll leave that to others. 

If I remember correctly, we eventually found a workaround by setting:

```python 
training_args = GRPOConfig(
        output_dir="Qwen2-0.5B-GRPO",
        bf16=True,
        use_vllm=True,
        vllm_mode=args.mode,
        vllm_tensor_parallel_size=1, #torch.cuda.device_count(),
        vllm_gpu_memory_utilization=0.5,
        report_to=[],
        logging_steps=1,
    )
```

Thanks for your time & effort on this issue.

**Comment by simonEllershaw** [comment]
I found

```
export NCCL_P2P_DISABLE=1
export NCCL_SHM_DISABLE=1
```

Solved this issue for me using multiple A100s, colocate, `accelerate v1.13.0`, `vllm v0.11.0` and ` trl v0.29.1`

Not 100% sure of the knock-on effects of this, though...
