### ISSUE TITLE
OOM when training qwen3-0.6B model by GRPO trainer on 20G VRAM GPU

### ISSUE THREAD

**Issue by wa008** [huggingface/trl#3678]
## Problem
OOM appear when training qwen3-0.6B model by GRPO trainer with max-prompt=256 and max-completions=256 on 20G VRAM GPU, possible main reason is that model-forward and backward consumed too much memory, using flash-attention may reduce consumed memory, I haven't try it yet. 

I'm not sure whether this's reasonable. 

## not related with old verison 
I test it on 0.14.0, 0.16.0, 0.17.0 and 0.19.0 version, it shows that every version didn't work well

## Possible main reason
I found that the most consuming GPU point is 
```
logits = model(
                input_ids=input_ids_batch,
                attention_mask=attention_mask_batch,
                logits_to_keep=logits_to_keep + 1,
            ).logits
```
[code](https://github.com/huggingface/trl/blob/e04f7eb3b993b5278733a793853ed3a85d1c69c8/trl/trainer/grpo_trainer.py#L879)

and, model init by `model = AutoModelForCausalLM.from_pretrained(model, **model_init_kwargs)`

when doing model forward, consumed memory increased from 8B into 20G, which result in OOM in the next training step, so, the main reason why trl GRPO consume so much memory is related with model-forward(with backward) function rather than trl repository. 

## Reproduce 
model: Qwen3-0.6B
GPU: 20G memory
data: longest input is 168

full data: 
```
[
	{
        "prompt": [
            {
                "role": "user",
                "content": "what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning?what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning? what is machine learning?"
            }
        ]
    },
    {
        "prompt": [
            {
                "role": "user",
                "content": "why sky is blue?"
            }
        ]
    }
]
```

code:
```
from datasets import load_dataset
from trl import GRPOConfig, GRPOTrainer
import os

# dataset = load_dataset("/root/.cache/modelscope/hub/datasets/okwinds/tldr/data", split="train")
dataset = load_dataset("data_custom", split = 'train')
print (type(dataset))

# Define the reward function, which rewards completions that are close to 20 characters
def reward_len(completions, **kwargs):
    return [-abs(20 - len(completion)) for completion in completions]

training_args = GRPOConfig(output_dir="Qwen3-0.6B-GRPO",
        max_prompt_length = 512,
        max_completion_length = 512,
        num_generations = 4,
        gradient_accumulation_steps = 1,
        use_vllm = True,
        vllm_mode = 'colocate',
        vllm_gpu_memory_utilization = 0.1,
        per_device_train_batch_size = 4,
        num_train_epochs = 1
    )
trainer = GRPOTrainer(
    model="/root/.cache/modelscope/hub/models/Qwen/Qwen3-0.6B",
    reward_funcs=reward_len,
    args=training_args,
    train_dataset=dataset,
)
trainer.train()
```

nvidia-smi
```
Wed Jul  2 18:17:04 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     On  |   00000000:DC:00.0 Off |                  N/A |
| 20%   29C    P8             52W /  250W |       1MiB /  22528MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

error: 
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/autodl-tmp/grpotrainer.py", line 30, in <module>
[rank0]:     trainer.train()
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/transformers/trainer.py", line 2207, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/transformers/trainer.py", line 2549, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/transformers/trainer.py", line 3750, in training_step
[rank0]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/trl/extras/profiling.py", line 98, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/trl/trainer/grpo_trainer.py", line 1480, in compute_loss
[rank0]:     return self._compute_loss(model, inputs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/trl/trainer/grpo_trainer.py", line 1507, in _compute_loss
[rank0]:     per_token_logps = self._get_per_token_logps_and_entropies(
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/trl/extras/profiling.py", line 98, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/trl/trainer/grpo_trainer.py", line 927, in _get_per_token_logps_and_entropies
[rank0]:     logits = model(
[rank0]:              ^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/parallel/distributed.py", line 1637, in forward
[rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/parallel/distributed.py", line 1464, in _run_ddp_forward
[rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/utils/operations.py", line 818, in forward
[rank0]:     return model_forward(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/utils/operations.py", line 806, in __call__
[rank0]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/utils/operations.py", line 785, in convert_to_fp32
[rank0]:     return recursively_apply(_convert_to_fp32, tensor, test_type=_is_fp16_bf16_tensor)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/utils/operations.py", line 119, in recursively_apply
[rank0]:     k: recursively_apply(
[rank0]:        ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/utils/operations.py", line 126, in recursively_apply
[rank0]:     return func(data, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/accelerate/utils/operations.py", line 777, in _convert_to_fp32
[rank0]:     return tensor.float()
[rank0]:            ^^^^^^^^^^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.16 GiB. GPU 0 has a total capacity of 21.66 GiB of which 259.69 MiB is free. Process 190234 has 21.39 GiB memory in use. Of the allocated memory 19.86 GiB is allocated by PyTorch, with 2.00 MiB allocated in private pools (e.g., CUDA Graphs), and 779.59 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W702 17:38:34.431805506 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
 50%|█████     | 1/2 [01:58<01:58, 118.97s/it]
```

related issue: 
- https://github.com/huggingface/trl/issues/3456
- https://github.com/huggingface/trl/issues/3664

### System Info

trl env:
```
INFO 07-02 18:25:41 [__init__.py:244] Automatically detected platform cuda.

Copy-paste the following information when reporting an issue:

- Platform: Linux-5.15.0-94-generic-x86_64-with-glibc2.31
- Python version: 3.12.3
- TRL version: 0.20.0.dev0
- PyTorch version: 2.7.0
- accelerator(s): NVIDIA GeForce RTX 2080 Ti
- Transformers version: 4.53.0
- Accelerate version: 1.8.1
- Accelerate config: not found
- Datasets version: 3.6.0
- HF Hub version: 0.33.1
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.93.0
- PEFT version: not installed
- vLLM version: 0.9.1
```

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by shirinyamani** [comment]
Hi @wa008 thanks for reporting, lemme check! but a couple of questions;
1. have you tried to increase the `vllm_gpu_memory_utilization`?
2. i assume the `data_custom` is what you pasted above? (fro reproduction purposes)

**Comment by wa008** [comment]
> Hi [@wa008](https://github.com/wa008) thanks for reporting, lemme check! but a couple of questions;
> 
> 1. have you tried to increase the `vllm_gpu_memory_utilization`?
> 2. i assume the `data_custom` is what you pasted above? (fro reproduction purposes)

Thanks for your attention

1. I tried default value (0.9), same error appear. out of memory appear when set vllm_gpu_memory_utilization 0.1, increase this parameter will result in less memory for grpo? 
2. yes

**Comment by shirinyamani** [comment]
Hi @wa008  Yes, i tried, and you are so right!
so inspecting on this + [this similar issue](https://github.com/huggingface/trl/issues/3701) of OOM, I believe the forward pass is perhaps bottleneck especially when the prompt+com are toooo lengthy! 
I perhaps wanna try out the approach discuss in the other issue, the approach of forwarding serially after each prompt, not sure its gonna be a better gain, but please lemme know if you think of any other solution

**Comment by wa008** [comment]
> Hi [@wa008](https://github.com/wa008) Yes, i tried, and you are so right! so inspecting on this + [this similar issue](https://github.com/huggingface/trl/issues/3701) of OOM, I believe the forward pass is perhaps bottleneck especially when the prompt+com are toooo lengthy! I perhaps wanna try out the approach discuss in the other issue, the approach of forwarding serially after each prompt, not sure its gonna be a better gain, but please lemme know if you think of any other solution

Appreciated for your work. 

trl doesn't use flash-attention by default, is it possible to detect env(python version, pytorch, cuda version) to use flash-attention if env is compatible, or remind user to update env to use flash-attention

**Comment by wa008** [comment]
Forward only once for each different input rather than forward `num_generation` times can decrease necessary VRAM. 

reference: https://arxiv.org/pdf/2506.05433

**Comment by akshansh47** [comment]
The OP correctly identified the LM head materialization as the culprit. We hit
the same class of OOM at 27B scale; the relevant subset for small-model + 20 GB:

- **`PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`** — typically reclaims
  2-5 GB/GPU on long-context runs, free optimization, no training-dynamics risk.
- **`attn_implementation="flash_attention_2"`** at model load — eager softmax
  materializes a full `[B, H, S, S]` matrix; FA2 replaces it with online softmax,
  big win at prompt+completion ≥ 256 each.
- **Per-step `gc.collect() + torch.cuda.empty_cache()`** between rollouts and
  trainer steps. Refs accumulate from policy + ref_model + LM head clones; the
  cache release alone has unblocked OOMs that surfaced ~step 50+.
- **Vocab-axis chunked LM head** instead of materializing `[B, S, V]` logits.
  Halve-the-chunk on `OutOfMemoryError` before falling back to dense.
- **Last-resort:** `accelerate launch --deepspeed_config_file` with
  `offload_optimizer.device=cpu` (~10–15% throughput hit, but rescues OOM).

Minimum env that fixes the fragmentation half:

```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
PYTORCH_ALLOC_CONF=expandable_segments:True   # canonical name for torch >= 2.11
```

Set both — older torch only reads `PYTORCH_CUDA_ALLOC_CONF`, newer prefers
`PYTORCH_ALLOC_CONF`. Note: incompatible with vLLM's `CuMemAllocator` if you're
running colocated rollouts; clear it before `Ray.init()` in that case.

**Comment by behroozazarkhalili** [comment]
I measured this on a single H100 to pin down where the memory goes, and there's a concrete, already-available fix.

## Where the memory goes (measured)

Instrumenting `_get_per_token_logps_and_entropies` (the forward you pointed at) on `trl-internal-testing/tiny-Qwen2ForCausalLM-2.5`, `B=2`, `logits_to_keep=256`, bf16:

| quantity | value |
|---|---|
| full logits tensor `[B, logits_to_keep, vocab]` (`2 × 256 × 151665`, bf16) | **310 MB** |
| peak CUDA allocated across the logprob forward | **902 MB** |
| allocated before the forward | 44 MB |

The full-logits tensor is the dominant single allocation, and it scales as **`batch × completion_length × vocab`** — note it's the **vocab (151k)** that dominates, *not* the model size. That's why a 0.6 B model still OOMs at 20 GB once you have a real batch × `num_generations` × completion length: the logits dwarf the model. The existing batch-chunking in `_get_per_token_logps_and_entropies` helps, but each micro-batch still materializes `[bs, keep, vocab]`.

## The fix: `use_liger_kernel=True`

GRPO already has a memory-efficient loss path that avoids ever materializing the full logits — `LigerFusedLinearGRPOLoss`, enabled with `use_liger_kernel=True` (requires `pip install liger-kernel`). It multiplies the hidden states by `lm_head.weight` in a fused/chunked kernel, so the `[B, keep, vocab]` logits are never held in full. transformers documents Liger as roughly **+20% throughput / −60% memory**, and here it targets exactly the 310 MB tensor above.

```python
training_args = GRPOConfig(
    ...,
    use_liger_kernel=True,   # fused GRPO loss, no full-logits materialization
)
```

(This is the GRPO analog of SFT's `loss_type="chunked_nll"`, which solves the same full-logits problem for supervised fine-tuning.)

Other knobs that stack on top, in rough order of impact for the small-model / low-VRAM case:
- `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` — reduces fragmentation.
- lower `num_generations` / `max_completion_length` — both scale the logits tensor linearly.
- gradient checkpointing.

cc @shirinyamani @qgallouedec — given the thread already isolated the forward as the bottleneck, would it be worth calling out `use_liger_kernel=True` in the GRPO memory docs as the first thing to try for this OOM class? Happy to open a small docs PR if useful.

**Comment by albertvillanova** [comment]
Hi @wa008, sorry for the very slow follow-up — we're catching up on the backlog. 

You (and @behroozazarkhalili's measurements) nailed the root cause: this isn't a leak, it's the expected cost of the log-prob forward, where the `[batch × completion_length × vocab]` logits tensor dominates — and it's the 151k vocab, not the 0.6B model, that drives it (which is why a tiny model still OOMs at 20 GB). 

GRPO already ships a memory-efficient path that never materializes those full logits: set `use_liger_kernel=True` (`pip install "trl[liger]"`). Stacking `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`, gradient checkpointing, and lower `num_generations`/`max_completion_length` on top covers the low-VRAM case — all collected in the Reducing Memory Usage guide: 
- https://huggingface.co/docs/trl/v1.8.0/en/reducing_memory_usage#liger-for-reducing-peak-memory-usage
- https://github.com/huggingface/trl/blob/6987bd89d03d164f23f54c20d5681ee2e09733f3/docs/source/reducing_memory_usage.md#L127-L159 . 

Closing as intended behavior, but happy to reopen if `use_liger_kernel=True` still OOMs on your setup and you can share the new `trl env` + trace.
