### ISSUE TITLE
trl with vllm integration not working

### ISSUE THREAD

**Issue by PodoprikhinMaxim** [huggingface/trl#3706]
### Reproduction

I am trying to run trl with vllm integration and get with `.init_communicator()` problem:

run vllm server with
```
CUDA_VISIBLE_DEVICES=0,1,2 trl vllm-serve --model Qwen/Qwen2-0.5B --tensor-parallel-size 2 --data-parallel-size 1 --port=8000
```

and main script is just

```
from trl.extras.vllm_client import VLLMClient

vllm_client = VLLMClient(
    "http://0.0.0.0:8000",
    connection_timeout=10
)
print("started init_communicator")
vllm_client.init_communicator()
print("done!")
```

Error log:

```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:     [127.0.0.1:39726](http://127.0.0.1:39726/) - "GET /health/ HTTP/1.1" 200 OK
INFO:     [127.0.0.1:39728](http://127.0.0.1:39728/) - "GET /get_world_size/ HTTP/1.1" 200 OK
INFO:     [127.0.0.1:39744](http://127.0.0.1:39744/) - "POST /init_communicator/ HTTP/1.1" 200 OK
(VllmWorker rank=1 pid=4888) INFO 07-08 10:09:09 [utils.py:1126] Found nccl from library libnccl.so.2
(VllmWorker rank=1 pid=4888) INFO 07-08 10:09:09 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorker rank=0 pid=4887) INFO 07-08 10:09:09 [utils.py:1126] Found nccl from library libnccl.so.2
(VllmWorker rank=0 pid=4887) INFO 07-08 10:09:09 [pynccl.py:70] vLLM is using nccl==2.26.2

[2025-07-08 10:09:09] research-cluster-podoprihin-2em:4887:4887 [0] init.cc:722 NCCL WARN Duplicate GPU detected : rank 0 and rank 2 both on CUDA device 85000
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527] WorkerProc hit an exception.
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527] Traceback (most recent call last):
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 522, in worker_busy_loop
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]     output = func(*args, **kwargs)
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/trl/scripts/vllm_serve.py", line 108, in init_communicator
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]     self.pynccl_comm = PyNcclCommunicator(pg, device=self.device)
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl.py", line 100, in __init__
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 278, in ncclCommInitRank
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 257, in NCCL_CHECK
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorker rank=0 pid=4887) ERROR 07-08 10:09:09 [multiproc_executor.py:527] RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
ERROR 07-08 10:09:09 [core.py:583] Invocation of collective_rpc method failed
ERROR 07-08 10:09:09 [core.py:583] Traceback (most recent call last):
ERROR 07-08 10:09:09 [core.py:583]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 580, in _handle_client_request
ERROR 07-08 10:09:09 [core.py:583]     output.result = method(
ERROR 07-08 10:09:09 [core.py:583]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 347, in collective_rpc
ERROR 07-08 10:09:09 [core.py:583]     return self.model_executor.collective_rpc(method, timeout, args,
ERROR 07-08 10:09:09 [core.py:583]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 220, in collective_rpc
ERROR 07-08 10:09:09 [core.py:583]     result = get_response(w, dequeue_timeout)
ERROR 07-08 10:09:09 [core.py:583]   File "/home/podoprihin.m/benchmarks_to_sft/venv_trl_vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 207, in get_response
ERROR 07-08 10:09:09 [core.py:583]     raise RuntimeError(
ERROR 07-08 10:09:09 [core.py:583] RuntimeError: Worker failed with error 'NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)', please check the stack trace above for the root cause
```

The only thing that was installed is `vllm[trl]`

### System Info

- Platform: Linux-6.1.0-21-amd64-x86_64-with-glibc2.35
- Python version: 3.10.12
- TRL version: 0.19.0
- PyTorch version: 2.7.0
- accelerator(s): NVIDIA A800 80GB PCIe, NVIDIA A800 80GB PCIe, NVIDIA A800 80GB PCIe
- Transformers version: 4.53.1
- Accelerate version: 1.8.1
- Accelerate config: not found
- Datasets version: 3.6.0
- HF Hub version: 0.33.2
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.93.0
- PEFT version: not installed
- vLLM version: 0.9.1

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by RageItalic** [comment]
Im having a similar issue, though I'm not even using vllm in my code. From what I can tell, vllm (at least 0.9 and above) is not compatible with pytorch  2.7.0. It needs pytorch 2.6.0. I've tried downgrading my pytorch version but no luck for me. Do report back here if you are able to get it to work by downgrading or some other way.

**Comment by willccbb** [comment]
will cause a performance hit on your weight syncing, but you should be able to set `NCCL_P2P_DISABLE=1` to get around this

**Comment by PodoprikhinMaxim** [comment]
> Im having a similar issue, though I'm not even using vllm in my code. From what I can tell, vllm (at least 0.9 and above) is not compatible with pytorch 2.7.0. It needs pytorch 2.6.0. I've tried downgrading my pytorch version but no luck for me. Do report back here if you are able to get it to work by downgrading or some other way.

tried pytorch 2.6.0, but vllm 0.9.2 requires pytorch 2.7.0 version

**Comment by PodoprikhinMaxim** [comment]
> will cause a performance hit on your weight syncing, but you should be able to set `NCCL_P2P_DISABLE=1` to get around this

did't help(

**Comment by ssenichev** [comment]
+1, same error using vllm==0.9.2 and torch==2.7.0; 
tried using vllm==0.9.2+torch==2.6.0 and vllm==0.8.5+torch==2.6.0 - didn't help

**Comment by CarlosArguilar** [comment]
For the information provided, the issue is trying to use the same device for the vllm server and vllm client.

When `vllm_client.init_communicator` is called it creates a NCCL communicator that has the ranks corresponding to the vllm workers and the trainer main process. But the NCCL communicator does not support different ranks being in the same device:

[Docs NCCL Communicator](https://docs.nvidia.com/deeplearning/nccl/archives/nccl_2262/user-guide/docs/usage/communicators.html)
> Using the same CUDA device multiple times as different ranks of the same NCCL communicator is not supported and may lead to hangs.

Even though it is warned in the trl documentation regarding vllm server that this may lead to conflict, it is not being enforced by the code. I'm drafting a PR that will add a verification for this conflict to avoid this kind of situation.

In summary, ensure by setting the `CUDA_VISIBLE_DEVICES` variable that the vllm server and trainer (or VLLMClient if you are using it by itself like in the example) are placed in different devices. In your specific example, if you have three GPUs you must not use all of them for the server if you are calling a trainer that will use VLLMClient.

So you could run the server like this to avoid this problem:
```CUDA_VISIBLE_DEVICES=1,2 trl vllm-serve --model Qwen/Qwen2-0.5B --tensor-parallel-size 2 --data-parallel-size 1 --port=8000```

And then run your script in the device that is not being used by the server:
```CUDA_VISIBLE_DEVICES=0 python main_script.py```

**Comment by merveenoyan** [comment]
Running vLLM in 1,2 and GRPO process in GPU 4 solved it for me! Thanks @CarlosArguilar I didn't notice I was using both devices for all. 

if that's the case btw, you can use `colocate` it will spawn training + serving in same devices.

**Comment by qgallouedec** [comment]
Hey @PodoprikhinMaxim, sorry for the very slow reply here, we're catching up on the backlog.

This isn't a TRL bug: the `NCCL WARN Duplicate GPU detected: rank 0 and rank 2 both on CUDA device` error means the vLLM server and the client/trainer are being placed on the same CUDA device, which NCCL doesn't support (one device can't be two distinct ranks in the same communicator). Your command hands all three GPUs (`0,1,2`) to the server with `--tensor-parallel-size 2`, so the client process defaults to `cuda:0` and collides with server rank 0.
As @CarlosArguilar noted, keep them on separate devices (e.g. `CUDA_VISIBLE_DEVICES=1,2 trl vllm-serve ...` for the server and `CUDA_VISIBLE_DEVICES=0 python main_script.py` for the client).

Since then we've also added a guard (#3762) so current TRL raises a clear error about this instead of the cryptic NCCL one, see https://github.com/huggingface/trl/blob/fceadc75c81bd103a6cf7f870eafddf1106b6065/trl/scripts/vllm_serve.py#L89-L93.
