### ISSUE TITLE
RuntimeError on calling the `self.generate_on_policy_outputs` function during `GKDTrainer` training loop

### ISSUE THREAD

**Issue by NoviceStone** [huggingface/trl#4869]
### Reproduction

I am trying to use the **On-Policy Distillation** algorithm to transfer knowledge from the teacher model (Qwen3-32B) to the student model (Qwen3-1.7B).

Below is the detailed script command I have used.
```bash
accelerate launch \
  --config_file examples/accelerate_configs/multi_gpu.yaml examples/scripts/gkd.py \
  --model_name_or_path Qwen/Qwen3-1.7B \
  --dtype auto \
  --attn_implementation flash_attention_2 \
  --dataset_name data/Veribench-9K-student-qwen3-1.7b-teacher-qwen3-32b-messages.jsonl \
  --bf16 true \
  --learning_rate 1e-5 \
  --gradient_checkpointing true \
  --per_device_train_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --num_train_epochs 1 \
  --temperature 0.6 \
  --max_new_tokens 1024 \
  --lmbda 1.0 \
  --beta 1.0 \
  --teacher_model_name_or_path Qwen/Qwen3-32B \
  --logging_steps 1 \
  --report_to tensorboard \
  --output_dir outputs/Qwen3-1.7B-GKD-Veribench-Hard \
  --seed 42 \
  --warmup_ratio 0.05 \
  --lr_scheduler_type cosine_with_min_lr \
  --lr_scheduler_kwargs '{"min_lr": 1e-7}'
```

An RuntimeError occurred when executing the function `self.generate_on_policy_outputs` during the training step of `GKDTrainer`. The detailed log information is as follows:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/clap26/scripts/distillation/trl_main/examples/scripts/gkd.py", line 155, in <module>
[rank0]:     trainer.train()
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/trainer.py", line 2325, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/trainer.py", line 2674, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/trl/experimental/gkd/gkd_trainer.py", line 448, in training_step
[rank0]:     new_input_ids, new_attention_mask, new_labels = self.generate_on_policy_outputs(
[rank0]:                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/trl/experimental/gkd/gkd_trainer.py", line 396, in generate_on_policy_outputs
[rank0]:     generated_outputs = model.generate(
[rank0]:                         ^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/generation/utils.py", line 2564, in generate
[rank0]:     result = decoding_method(
[rank0]:              ^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/generation/utils.py", line 2784, in _sample
[rank0]:     outputs = self(**model_inputs, return_dict=True)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/accelerate/utils/operations.py", line 819, in forward
[rank0]:     return model_forward(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/accelerate/utils/operations.py", line 807, in __call__
[rank0]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/utils/generic.py", line 918, in wrapper
[rank0]:     output = func(self, *args, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 480, in forward
[rank0]:     outputs: BaseModelOutputWithPast = self.model(
[rank0]:                                        ^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/utils/generic.py", line 1072, in wrapper
[rank0]:     outputs = func(self, *args, **kwargs)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 410, in forward
[rank0]:     hidden_states = decoder_layer(
[rank0]:                     ^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/modeling_layers.py", line 94, in __call__
[rank0]:     return super().__call__(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 260, in forward
[rank0]:     hidden_states, _ = self.self_attn(
[rank0]:                        ^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 200, in forward
[rank0]:     query_states = self.q_norm(self.q_proj(hidden_states).view(hidden_shape)).transpose(1, 2)
[rank0]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, -1, 128] because the unspecified dimension size -1 can be any value and is ambiguous
[rank0]:[W120 15:23:28.311607989 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[rank0]:[E120 15:36:15.799522869 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 0] ProcessGroupNCCL's watchdog got stuck for 480 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API (e.g., CudaEventDestroy) hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api (for example, CudaEventDestroy), or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. 
[rank0]:[E120 15:36:15.801103002 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 0] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank0]:[F120 15:44:15.804344483 ProcessGroupNCCL.cpp:1600] [PG ID 0 PG GUID 0(default_pg) Rank 0] [PG ID 0 PG GUID 0(default_pg) Rank 0] Terminating the process after attempting to dump debug info, due to ProcessGroupNCCL watchdog hang.
W0120 15:44:15.816000 1989142 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1989377 closing signal SIGTERM
W0120 15:44:15.817000 1989142 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1989378 closing signal SIGTERM
W0120 15:44:15.818000 1989142 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1989379 closing signal SIGTERM
W0120 15:44:15.819000 1989142 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1989380 closing signal SIGTERM
W0120 15:44:15.820000 1989142 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1989381 closing signal SIGTERM
W0120 15:44:15.821000 1989142 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1989382 closing signal SIGTERM
W0120 15:44:15.822000 1989142 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1989383 closing signal SIGTERM
E0120 15:44:17.653000 1989142 torch/distributed/elastic/multiprocessing/api.py:882] failed (exitcode: -6) local_rank: 0 (pid: 1989376) of binary: /home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/bin/python
Traceback (most recent call last):
  File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/bin/accelerate", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1272, in launch_command
    multi_gpu_launcher(args)
  File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/accelerate/commands/launch.py", line 899, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/distributed/run.py", line 927, in run
    elastic_launch(
  File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 156, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpu1/SAIT_HQ_XIAN/share/SOLVE/xys/supercom_envs/trl/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 293, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
examples/scripts/gkd.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2026-01-20_15:44:15
  host      : hgpu8076
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 1989376)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 1989376
========================================================
```

### System Info

- Platform: Linux-5.14.0-284.11.1.el9_2.x86_64-x86_64-with-glibc2.34
- Python version: 3.12.3
- TRL version: 0.27.0.dev0
- PyTorch version: 2.9.0
- accelerator(s): NVIDIA H100 80GB HBM3
- Transformers version: 4.57.3
- Accelerate version: 1.12.0
- Accelerate config: not found
- Datasets version: 4.4.2
- HF Hub version: 0.36.0
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Liger-Kernel version: 0.6.4
- LLM-Blender version: not installed
- OpenAI version: 2.15.0
- PEFT version: not installed
- vLLM version: 0.12.0

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [ ] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by NoviceStone** [comment]
The issue has been resolved by changing `--config-file` from `examples/accelerate_configs/multi_gpu.yaml` to `examples/accelerate_configs/deepspeed_zero3.yaml` and `--gradient_checkpointing` from `true` to `false`.

**Comment by JeffLee1874** [comment]
Hi, do you know how to solved this with --gradient_checkpointing?
