### ISSUE TITLE
CUDA OOM while loading Llama2 

### ISSUE THREAD

**Issue by RitheshRn** [huggingface/trl#841]
Hi-

I tried running stack_llama_2 based on the instructions provided in the README [here](https://github.com/huggingface/trl/tree/main/examples/research_projects/stack_llama_2/scripts)

I can successfully run the first step i.e. SFT. However, I get an OOM error when I run the DPO trainer script. I am merely following the steps provided in the instructions without any changes.

I am using an 8 x A100 (40 GB) machine. **I see that when the system starts loading the llama2-7b model (i.e. while running [this line](https://github.com/huggingface/trl/blob/ac0d5b726d5c91d0cec87d9678815aaa88bdeb3b/examples/research_projects/stack_llama_2/scripts/dpo_llama2.py#L127) in the script), GPU:0's memory consumption shoots up and reaches the maximum limit.** 

Here is the terminal output: [terminal_output.txt](https://github.com/huggingface/trl/files/12834590/terminal_output.txt)

Any suggestions or tips are appreciated. Thank you!

**Comment by lvwerra** [comment]
Hi @RitheshRn, are you able to load the model with that line alone on a single GPU or is this also causing issues. cc @younesbelkada who knows more about loading models with PEFT and quantization.

**Comment by younesbelkada** [comment]
Hi @RitheshRn 
as leandro suggested, can you first try to run the script on a single GPU? `CUDA_VISIBLE_DEVICES=0 python xxxx.py` 
In case you are trying to run it on multi-GPU + DDP you need to add a small trick to correctly place the model into each GPU

```python
from accelerate import Accelerator

device_index = Accelerator().process_index

model = AutoModelForCausalLM.from_pretrained(
    model_id=model_id,
    load_in_4bit=True,
    device_map={"": device_index}
)
```

That way the model will be correctly loaded independently into each GPU instead of trying to fit everything sequentially on all GPUs

**Comment by RitheshRn** [comment]
Thank you! I resolved the error using the following code:

```
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    model = AutoPeftModelForCausalLM.from_pretrained(
        "sft/final_checkpoint",
        quantization_config=bnb_config,
        device_map={"": Accelerator().local_process_index},
        trust_remote_code=True,
        use_auth_token=True,
    )

    model.config.use_cache = False

    model_ref = AutoPeftModelForCausalLM.from_pretrained(
        "sft/final_checkpoint",
        quantization_config=bnb_config,
        device_map={"": Accelerator().local_process_index},
        trust_remote_code=True,
        use_auth_token=True,
    )
```
