### ISSUE TITLE
0.7.4 consumes much more GPU memory than 0.5.0

### ISSUE THREAD

**Issue by zhourunlong** [huggingface/trl#999]
For the same script to finetune a `gpt2-xl` model with `8bit` and `bf16`, version 0.5.0 uses around 10GB of GPU mem, but version 0.7.4 gets OOM on a 4090, indicating that the memory consumption is larger than 24GB. Sorry that I cannot post my code here because of copyright issues, but I think this issue can be replicated easily.

**Comment by younesbelkada** [comment]
Hi @zhourunlong 
Thanks for the issue!
By default in the previous versions `gradient_checkpointing` was set to `True` whereas on the earlier versions you need to manually set it to `True`; can you make sure to add `gradient_checkpointing=True` on your training script?

**Comment by zhourunlong** [comment]
> Hi @zhourunlong Thanks for the issue! By default in the previous versions `gradient_checkpointing` was set to `True` whereas on the earlier versions you need to manually set it to `True`; can you make sure to add `gradient_checkpointing=True` on your training script?

Thanks for your reply! I manually set `gradient_checkpointing=True` in version 0.7.4 then the memory issue is back to 10GB. This resolves my issue.

I used `TrainingArguments` class in `transformers`. By default this class sets `gradient_checkpointing=False`. In version 0.5.0 the `SFTTrainer` doesn't use this argument in `__init__`. So this is in fact a bug fix :)
